public CausedIOException(String message, Throwable cause) {
    super(message);
    this.initCause(cause);
}